version: '3.6'

services:

  frontend:
    build:
      context: ./bhlog-front
      dockerfile: Dockerfile
    container_name: bhlog-front
    depends_on:
      - backend
    ports:
      - "80:80"
    expose:
      - 80

  backend:
    build:
      context: ./bhlog-back
      dockerfile: Dockerfile
    container_name: bhlog-back
    depends_on:
      - postgres-db
    ports:
      - "81:80"
    expose:
      - 81

  postgres-db:
    container_name: bhlog-db
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"